(BL-36) Do not clobber authorized_keys if download fails
Without this patch the `manage_root_authorized_keys` script will
overwrite the contents of `~root/.ssh/authorized_keys` in the event of a
download failure.  This is a problem because end users cannot log into
new elastic instances.  This patch addresses the problem by checking the
exit status of the download command and aborting the script before
writing to the authorized_keys file if the download does not complete
with a 0 exit status code.

diff --git a/templates/scripts/manage_root_authorized_keys b/templates/scripts/manage_root_authorized_keys
--- a/templates/scripts/manage_root_authorized_keys
+++ b/templates/scripts/manage_root_authorized_keys
@@ -44,8 +44,14 @@ then
   chown $OWNER:$GROUP $SSH_HOME/authorized_keys.tmp
 fi
 
-# Download the file.  If this fails the script will abort since we're set -e
+# Download the file.  Abort without modifying ~/.ssh/authorized_keys if this
+# step fails.
 $GET > $SSH_HOME/authorized_keys.tmp
+rval=$?
+if [[ $rval -ne 0 ]]; then
+  echo "Error: Download failed with exit status code $rval"
+  exit 1
+fi
 
 # Merge any local authorized_keys
 # Make sure there is no temporary file
